/* eslint-disable @next/next/no-page-custom-font */
import { Heading, Header, Footer } from 'components'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PocketSeat Community</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=IBM+Plex+Mono:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>Header goes here!</Header>
        <Heading>Heading goes here!</Heading>
      </main>

      <Footer>Footer goes here!</Footer>

    </div>
  )
}

export default Home
